version: '3.2'
services:
  dawapack_amqp_daemon:
    image: dawapack:0.1-amqp-daemon
    container_name: dawapack_amqp_daemon
    build:
      dockerfile: Dockerfile
      context: ./var/docker
    stdin_open: true
    tty: true
    environment:
      ORIGIN: "eu"
      REGION: "eu-bucharest-1"
    volumes:
      - type: bind
        source: ./src
        target: /var/www
