version: '3.2'
services:
  dawapack_amqp_daemon:
    image: dawapack:0.1-amqp-daemon
    container_name: dawapack_amqp_daemon
    build:
      dockerfile: Dockerfile
      context: ./var/docker
    stdin_open: true
    tty: true
    environment:
      ORIGIN: "eu"
      REGION: "eu-bucharest-1"
    volumes:
      - type: bind
        source: ./src
        target: /var/www
  rabbitmq:
    image: rabbitmq:3.9.0-management-alpine
    container_name: dawapack_rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:6.2-alpine
    container_name: dawapack_redis
    restart: on-failure
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
