#!/usr/bin/env php
<?php
declare(strict_types=1);

use DaWaPack\Chassis\Application;
use DaWaPack\Classes\Daemon\Kernel;

define('RUNNER_TYPE', 'daemon');

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
*/
/** @var Application $app */
$app = require __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Create the kernel instance in the runner context type
|--------------------------------------------------------------------------
*/
$kernel = new Kernel($app);
$kernel->boot();
