#!/usr/bin/env php
<?php

declare(strict_types=1);

use DaWaPack\Chassis\Application;
use DaWaPack\Kernel;
use DaWaPack\Providers\WorkerRoutingServiceProvider;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
*/
/** @var Application $app */
$app = require __DIR__ . '/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Load configuration files
|--------------------------------------------------------------------------
*/
// uncomment this line and replace file by the config file you want to load
//$app->withConfig("file");

/*
|--------------------------------------------------------------------------
| Register multi-threading
|--------------------------------------------------------------------------
*/
$app->withThreads();

/*
|--------------------------------------------------------------------------
| Register broker
|--------------------------------------------------------------------------
*/
$app->withBroker();

/*
|--------------------------------------------------------------------------
| Register interfaces, aliases, ...
|--------------------------------------------------------------------------
*/
//$app->add(MyInterface::class, MyConcrete::class)
//    ->addArguments(["argument", new InjectedDependecy()])

/*
|--------------------------------------------------------------------------
| Register service providers
|--------------------------------------------------------------------------
*/
//$app->addServiceProvider(new MyServiceProvider());

/*
|--------------------------------------------------------------------------
| Create the kernel instance in the runner context type
|--------------------------------------------------------------------------
*/
(new Kernel($app))->boot();
