#!/usr/bin/env php
<?php

declare(strict_types=1);

use Chassis\Application;
use Chassis\Framework\Kernel;
use DaWaPack\Providers\RequestRoutingServiceProvider;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
*/
/** @var Application $app */
$app = require __DIR__ . '/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Register multi-threading
|--------------------------------------------------------------------------
*/
$app->withThreads();

/*
|--------------------------------------------------------------------------
| Register broker
|--------------------------------------------------------------------------
*/
$app->withBroker();

/*
|--------------------------------------------------------------------------
| Add container aliases
|--------------------------------------------------------------------------
*/
$app->addServiceProvider(new RequestRoutingServiceProvider());

/*
|--------------------------------------------------------------------------
| Create the kernel instance in the runner context type
|--------------------------------------------------------------------------
*/
(new Kernel($app))->boot();
