name: PHPUnit Tests

on:
  push:
    branches: [ testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: |
          cp docker-compose.sample.yml docker-compose.yml
          docker-compose build
          docker-compose up -d
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: PHPUnit tests
        run: docker exec -it dawapack_amqp_daemon ./vendor/bin/phpunit tests --coverage-text
