name: PHPUnit Tests

on:
  push:
    branches: [ testci ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: php:7.4-zts

    steps:
      - name: Init Docker Image
        run: |
          apt-get update
          apt-get install -y git
          pecl install parallel
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Test
        run: |
          ls -lsa
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          php composer-setup.php --install-dir=/usr/bin --filename=composer
          rm -rf composer-setup.php

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader 

      - name: Run PHPUnit
        run: src/vendor/bin/phpunit --coverage-text
