name: PHPUnit Tests

on:
  push:
    branches: [ testci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug
          extensions: parallel

      - name: Validate composer.json and composer.lock
        working-directory: src
        run: composer validate

      - name: Install dependencies
        working-directory: src
        run: composer install --no-progress --prefer-dist --optimize-autoloader 

      - name: Run PHPUnit
        working-directory: src
        run: src/vendor/bin/phpunit --coverage-text
